BlogApplication/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogApplication.Models;

namespace BlogApplication.Controllers
{
    public class LayoutController : Controller
    {
        BlogDbContext db = new BlogDbContext();

        public PartialViewResult Categories()
        {
            var categories = db.Categories.ToList();
            return PartialView(categories);
        }

    }
}

BlogApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>mylog</title>
    @Styles.Render("~/Css/css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/blog.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    <script src="~/Scripts/Layout/Categories.js"></script>
    <link href="~/Css/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="page-header">
            <a href="@Url.Action("Index","Home")" style="text-decoration:none;color:black"><h1>MyLog</h1></a>
        </div>
        <div class="span12" style="margin-bottom: 3px">
            <nav class="navbar navbar-default" role="navigation">
                <ul class="nav nav-tabs" id="MenuItems">
                    <li class="active"><a href="#">Home</a></li>                  
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Contact</a></li>
                    <li style="margin-left: 380px;">
                        <ul class="navbar nav pull-right">
                            <li>
                                <input type="text" id="txtSearch" style="margin-top: 3px; margin-right: 2px" /></li>
                            <li>
                                <button type="button" class="btn btn-lg btn-primary" id="btnSearch">Search</button></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="span12">
            <div class="row">
                <div class="span3" style="background-color: #ffffff">
                   @{Html.RenderAction("Categories", "Layout");}
                </div>
                <div class="span9">
                    @RenderBody()
                </div>
            </div>
        </div>

    </div>
</body>
</html>